version: "3.8"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: bets
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  bot:
    build: .
    depends_on:
      - db
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      POSTGRES_DSN: postgresql+asyncpg://postgres:postgres@db:5432/bets
      TRACK_CHANNEL_ID: ${TRACK_CHANNEL_ID}
      CONFIDENCE_THRESHOLD: 0.9
      TESSERACT_CMD: /usr/bin/tesseract
    restart: unless-stopped

volumes:
  pgdata:
