version: "3.9"

services:
  bettrackingbot:
    build: .
    container_name: bettrackingbot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - CHANNEL_ID=${CHANNEL_ID}
      - DEBUG_LOGGING=true
      - USE_YOLO=false
      - USE_EASYOCR=false
    volumes:
      - ./tracked_bets.json:/app/tracked_bets.json
      - ./bets.db:/app/bets.db
      - ./data/training:/app/data/training
      - ./data/models:/app/data/models
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
